{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "executor-pod-agent.serviceAccountName" . }}
  labels:
    {{- include "executor-pod-agent.labels" . | nindent 4 }}
{{- end }}
